import type { Profile, Recipe, Week } from "@/lib/schemas";
import { computeTargets } from "@/lib/nutrition";
import { buildGroceryList } from "@/lib/grocery";
import type { CookbookSnapshot } from "@/lib/storage";

export const DEMO_PROFILES: Record<"lifter" | "parent" | "managed", Profile> = {
  lifter: {
    id: "demo-lifter",
    createdAt: "2026-01-01T00:00:00.000Z",
    intent: "performance",
    sex: "male",
    age: 20,
    heightCm: 183,
    weightKg: 82,
    activity: "very_active",
    goal: "gain",
    pace: "moderate",
    dietaryPattern: "none",
    allergies: [],
    dislikes: ["liver"],
    likedCuisines: ["mexican", "american", "japanese"],
    spice: "medium",
    maxCookMinutes: 45,
    skill: "comfortable",
    equipment: ["oven", "stovetop", "air_fryer", "blender", "grill"],
    weeklyBudgetUsd: 120,
    householdSize: 1,
    guardrails: [],
    showNumbers: true,
    unitSystem: "imperial",
  },
  parent: {
    id: "demo-parent",
    createdAt: "2026-01-01T00:00:00.000Z",
    intent: "everyday",
    sex: "female",
    age: 38,
    heightCm: 165,
    weightKg: 72,
    activity: "light",
    goal: "eat_better",
    dietaryPattern: "none",
    allergies: ["peanuts"],
    dislikes: ["anchovies"],
    likedCuisines: ["italian", "american", "mexican"],
    spice: "mild",
    maxCookMinutes: 30,
    skill: "beginner",
    equipment: ["oven", "stovetop", "microwave", "slow_cooker"],
    weeklyBudgetUsd: 150,
    householdSize: 4,
    guardrails: [],
    showNumbers: false,
    unitSystem: "imperial",
  },
  managed: {
    id: "demo-managed",
    createdAt: "2026-01-01T00:00:00.000Z",
    intent: "managed",
    sex: "male",
    age: 55,
    heightCm: 175,
    weightKg: 88,
    activity: "light",
    goal: "lose",
    pace: "slow",
    dietaryPattern: "mediterranean",
    allergies: [],
    dislikes: ["fried food"],
    likedCuisines: ["mediterranean", "american"],
    spice: "mild",
    maxCookMinutes: 45,
    skill: "comfortable",
    equipment: ["oven", "stovetop", "blender"],
    householdSize: 2,
    guardrails: ["low_sodium"],
    showNumbers: false,
    unitSystem: "metric",
  },
};

export function buildDemoSnapshot(): CookbookSnapshot {
  const profile = DEMO_PROFILES.lifter;
  const targets = computeTargets(profile);
  const weekId = "demo-week-1";
  const now = "2026-09-10T12:00:00.000Z";
  const recipes: Recipe[] = [
    {
      id: "demo-breakfast",
      title: "Skillet eggs and oats",
      emoji: "🍳",
      mealType: "breakfast",
      servings: 1,
      prepMinutes: 5,
      cookMinutes: 10,
      costEstimateUsd: 3,
      cuisine: "american",
      ingredients: [
        { name: "Eggs", amount: 3, unit: "each" },
        { name: "Rolled oats", amount: 80, unit: "g" },
        { name: "Banana", amount: 1, unit: "each" },
        { name: "Olive oil", amount: 1, unit: "tsp" },
      ],
      steps: [
        {
          title: "Toast the oats",
          text: "Warm 1 tsp olive oil, then toast 80 g rolled oats for 10 seconds.",
          timerSeconds: 10,
        },
        { title: "Eggs", text: "Scramble 3 each eggs and plate with 1 each banana." },
      ],
      nutritionPerServing: {
        calories: 720,
        proteinG: 38,
        carbsG: 72,
        fatG: 28,
        fiberG: 9,
        sodiumMg: 320,
        addedSugarG: 0,
      },
      nutritionSource: "ai_estimate",
      whyThisFitsYou: "About 720 calories and 38g protein to start the surplus day.",
      tags: ["batch", "demo"],
      madeCount: 0,
      makeAgain: true,
      weekId,
      createdAt: now,
    },
    {
      id: "demo-lunch",
      title: "Chicken rice bowl",
      emoji: "🥗",
      mealType: "lunch",
      servings: 2,
      prepMinutes: 10,
      cookMinutes: 20,
      costEstimateUsd: 7,
      cuisine: "mexican",
      ingredients: [
        { name: "Chicken breast", amount: 12, unit: "oz" },
        { name: "Rice", amount: 1, unit: "cup" },
        { name: "Spinach", amount: 2, unit: "cup" },
        { name: "Olive oil", amount: 1, unit: "tbsp" },
      ],
      steps: [
        { title: "Rice", text: "Cook 1 cup rice." },
        { title: "Chicken", text: "Sear 12 oz chicken breast in 1 tbsp olive oil, rest 10 seconds.", timerSeconds: 10 },
      ],
      nutritionPerServing: {
        calories: 850,
        proteinG: 58,
        carbsG: 80,
        fatG: 22,
        fiberG: 4,
        sodiumMg: 410,
        addedSugarG: 0,
      },
      nutritionSource: "ai_estimate",
      whyThisFitsYou: "Batch two servings: 58g protein and 850 calories each.",
      tags: ["batch", "demo"],
      madeCount: 1,
      makeAgain: false,
      weekId,
      createdAt: now,
    },
    {
      id: "demo-dinner",
      title: "Turkey chili",
      emoji: "🍲",
      mealType: "dinner",
      servings: 2,
      prepMinutes: 15,
      cookMinutes: 30,
      costEstimateUsd: 9,
      cuisine: "american",
      ingredients: [
        { name: "Ground turkey", amount: 1, unit: "lb" },
        { name: "Tomato", amount: 2, unit: "each" },
        { name: "Onion", amount: 1, unit: "each" },
        { name: "Cumin", amount: 1, unit: "tsp" },
      ],
      steps: [
        { title: "Sweat onion", text: "Cook 1 each onion until soft." },
        { title: "Simmer", text: "Add 1 lb ground turkey, 2 each tomato, and 1 tsp cumin. Simmer." },
      ],
      nutritionPerServing: {
        calories: 980,
        proteinG: 62,
        carbsG: 55,
        fatG: 38,
        fiberG: 11,
        sodiumMg: 520,
        addedSugarG: 3,
      },
      nutritionSource: "ai_estimate",
      whyThisFitsYou: "Dinner carries most of the surplus with 62g protein.",
      tags: ["batch", "demo"],
      madeCount: 0,
      makeAgain: true,
      weekId,
      createdAt: now,
    },
    {
      id: "demo-snack",
      title: "Greek yogurt cup",
      emoji: "🍎",
      mealType: "snack",
      servings: 1,
      prepMinutes: 2,
      cookMinutes: 0,
      costEstimateUsd: 2,
      cuisine: "american",
      ingredients: [
        { name: "Greek yogurt", amount: 200, unit: "g" },
        { name: "Apple", amount: 1, unit: "each" },
      ],
      steps: [{ title: "Assemble", text: "Bowl 200 g Greek yogurt with 1 each apple." }],
      nutritionPerServing: {
        calories: 280,
        proteinG: 20,
        carbsG: 32,
        fatG: 4,
        fiberG: 4,
        sodiumMg: 70,
        addedSugarG: 8,
      },
      nutritionSource: "ai_estimate",
      whyThisFitsYou: "A 280 calorie protein snack so the day still hits the surplus.",
      tags: ["demo"],
      madeCount: 0,
      makeAgain: false,
      weekId,
      createdAt: now,
    },
  ];

  const ids = {
    breakfast: "demo-breakfast",
    lunch: "demo-lunch",
    dinner: "demo-dinner",
    snack: "demo-snack",
  } as const;

  const week: Week = {
    id: weekId,
    number: 1,
    createdAt: now,
    profileSnapshot: profile,
    targets,
    days: [0, 1, 2, 3, 4, 5, 6].map((day) => ({
      day: day as 0 | 1 | 2 | 3 | 4 | 5 | 6,
      meals: [
        { mealType: "breakfast", recipeId: ids.breakfast },
        { mealType: "lunch", recipeId: ids.lunch },
        { mealType: "dinner", recipeId: ids.dinner },
        { mealType: "snack", recipeId: ids.snack },
      ],
    })),
    groceryList: buildGroceryList(recipes, []),
    summary:
      "Demo chapter only — not Claude-generated. High-protein batch cooking for a surplus week.",
  };

  return {
    profile,
    weeks: [week],
    recipes,
    checkIns: [
      { id: "demo-c1", date: "2026-09-01T12:00:00.000Z", weightKg: 82, energy: 4, hunger: 3 },
      { id: "demo-c2", date: "2026-09-08T12:00:00.000Z", weightKg: 83, energy: 3, hunger: 4 },
    ],
    pantry: [],
    usdaCache: {},
  };
}
